### ISSUE TITLE
[Issue] Mod get ignored by server

### ISSUE THREAD

**Issue by Taknax** [Gilded-Games/The-Aether-Archived#125]
This i get in my server console:
https://pastebin.com/HS7GfUQ1

I used the 1.5.3.1 version before without problems. After i updated 1.5.3.2 this issue occure. By Updating i deleted the world and the aether related configs, to avoid corruption (Also i deleted everything and installed new). The server is on ApexHosting and run the new forge 14.23.5.2855. 

Here is the Crashlog
https://pastebin.com/DrmzF9wx

**Comment by bconlon1** [comment]
You don't actually seem to have reinstalled Aether correctly, I can't see it in your mods list. The error is likely because the Aether addons can't find the mod.
