### ISSUE TITLE
Falling off the Aether islands

### ISSUE THREAD

**Issue by dazadazu** [Gilded-Games/The-Aether-Archived#135]
I used to be able to actually fall and sometimes float with a glider or cloud. But now when I fall it says

"A pelican has snatched you from the void." 

What gives? Actually falling was a great aspect of feeling how high it is.

**Comment by reetamb** [comment]
That's not from the Aether. It's from another mod. Gliders aren't even in the Aether mod.

**Comment by bconlon1** [comment]
This is not the fault of the Aether, I've never heard of this so I have no idea what other mod would be causing it.
