### ISSUE TITLE
Aether Dirt does not generate with terrain

### ISSUE THREAD

**Issue by NiaLoy** [Gilded-Games/The-Aether-Archived#144]
In version 1.5.3.X of the mod, for Minecraft 1.12.2, there is only one layer of Aether Grass on top of the Holystone with no dirt between.  All islands in the dimension generate this way.  This was not present in older builds of the mod.  Included are screenshots of an example and of a possible cause to the issue.

![1](https://user-images.githubusercontent.com/73674160/130536471-3029912b-1fe6-46db-8e11-1c58b7ffa0a0.png)
![2](https://user-images.githubusercontent.com/73674160/130536473-ae14dc56-00a5-44eb-89af-062ce93ce1e9.png)

**Comment by bconlon1** [comment]
Duplicate of #118.
