### ISSUE TITLE
Cant craft gloves

### ISSUE THREAD

**Issue by Metalteuffel** [Gilded-Games/The-Aether-Archived#151]
Not sure what's going on, they pop up in the item list, but going by YouTube videos and the wiki the recipe doesn't work. Hitting R on them doesn't show a recipe like for everything else.

**Comment by GaucovyAero** [comment]
Which version of Minecraft and Aether exactly are you on?

**Comment by Metalteuffel** [comment]
Java edition 1.17 and The Aether 1.17

**Comment by Alexmasonseals** [comment]
You're using aether reborn which is an unofficial mod made by a separate team, therefor, we can't give you any support since its not our mod.

make sure to go to their discord called immortal dev

**Comment by Metalteuffel** [comment]
Thank you very much
