### ISSUE TITLE
Nether portal "travel" sound plays regardless of if SPacketEffect is sent to the client

### ISSUE THREAD

**Issue by ubergeek77** [Gilded-Games/The-Aether-Archived#26]
For some unknown reason, regardless of whether or not the following line is present, the Nether Portal Travel sound will play after the player has switched dimensions via an Aether portal:

https://github.com/Gilded-Games/The-Aether-Archived/blob/1.12.2/src/main/java/com/gildedgames/the_aether/world/TeleporterAether.java#L65

For reference, the sound can be heard on [this page](https://minecraft.gamepedia.com/Nether_Portal_%28block%29) under `block.portal.travel`.

The above line sends an `SPacketEffect` to the client with ID `1032`. That ID corresponds to the vanilla sound effect `BLOCK_PORTAL_TRAVEL`, the Nether Portal "Travel" sound. This will make that sound effect play on the client just after they load into their destination dimension after stepping through an Aether portal.

If you were to *remove* this line, the Nether Portal "Travel" sound sound will still play. If you were to change this ID to a different sound, such as an anvil sound (`1031`), ***both*** sounds will play - the anvil sound and the Nether portal "Travel" sound.

Since the Nether portal travel sound plays somewhere else regardless of this line, leaving it as `1032` will cause the travel sound to play twice - once via `SPacketEffect`, and once in some unknown location.

Rather than just remove this line as a solution, I think it would be worth investigating where exactly this sound is coming from. Personally, I'm looking to change it to the Aether II's cool synth sound effect for myself, but without any explanation as to why the Nether travel sound is playing, it can't be changed.

For debugging purposes, to make it easier to hear this issue, it may be helpful to comment out the following two lines to mute the cocophony of noises that would otherwise play:

https://github.com/Gilded-Games/The-Aether-Archived/blob/1.12.2/src/main/java/com/gildedgames/the_aether/client/AetherClientEvents.java#L92

https://github.com/Gilded-Games/The-Aether-Archived/blob/1.12.2/src/main/java/com/gildedgames/the_aether/blocks/portal/BlockAetherPortal.java#L134

Note that the issue is still present regardless of if you comment out these two lines. I just find it easier to hear the issue without them.

**Comment by bconlon1** [comment]
A related issue to this seems to be that having a large Aether Portal creates tons of portal sounds. I need to see how vanilla handles portal sounds.

**Comment by ubergeek77** [comment]
> A related issue to this seems to be that having a large Aether Portal creates tons of portal sounds. I need to see how vanilla handles portal sounds.

Just the travel sound after loading into a new dimension, or the idle sounds when standing next to a portal?

If you're talking about just the idle sounds, then it may not necessarily be a vanilla thing:

https://github.com/Gilded-Games/The-Aether-Archived/blob/1.12.2/src/main/java/com/gildedgames/the_aether/blocks/portal/BlockAetherPortal.java#L134

It seems here that The Aether is randomly deciding when to play portal sounds, every tick, *for every portal block*. Maybe having a lot of portal blocks at once (in a large portal) is leading to the tons of portal sounds.

**Comment by bconlon1** [comment]
Yeah based on an issue someone mentioned in the discord, having a lot of portal blocks at once is supposedly causing a lot of portal sounds.

**Comment by bconlon1** [comment]
Relevant video: https://www.youtube.com/watch?v=6WHyuaUfLsU&feature=youtu.be

**Comment by bconlon1** [comment]
Checking with vanilla the having a lot of portal sounds thing seems intentional.

**Comment by bconlon1** [comment]
Fixed and will be in the next release.
