### ISSUE TITLE
Change biome provider to be more flexible

### ISSUE THREAD

**Issue by Foreck1** [Gilded-Games/The-Aether-Archived#28]
The current version of the mod uses the harcoded BiomeProviderSingle

The mod should ideally have configurable list of biomes so that other mods can hook onto the generation of the Aether dimension, thus, mods like BiomeTweaker could interact with it. This is, above all, a technical request for modpack makers who want to flesh out the dimension.

P.S. pretty sure this is not relevant for gilded games at this point, but I would be truly awesome if this feature could make it to 1.12 too.

**Comment by bconlon1** [comment]
Aether no longer uses BiomeProviderSingle so now I just need to add BiomeTweaker support.

**Comment by bconlon1** [comment]
Fully fixed and will be ready next release; a config has been added to allow adding biomes to the Aether dimension and it appears to be fully compatible with BiomeTweaker's custom biomes.
