### ISSUE TITLE
Shards of life can constantly increase max health even after they are no longer being used

### ISSUE THREAD

**Issue by reetamb** [Gilded-Games/The-Aether-Archived#30]
See discord message links: https://discord.com/channels/118816101936267265/229460143912255488/785771662955905064 and https://discord.com/channels/118816101936267265/569973116621684786/783394032076193864

**Comment by bconlon1** [comment]
https://github.com/gildedgames/aether-issues/issues/743
Seems to be an instance of this issue. It has had two other reports so I should probably look into this.

**Comment by bconlon1** [comment]
So when cloning your character or something (some data transfer event), it bugs the life shards and can give you infinite health.

**Comment by bconlon1** [comment]
Hearts also can double upon death.

**Comment by bconlon1** [comment]
Can also occur during dimension transfer.

**Comment by bconlon1** [comment]
lifeShardCount appears to be duplicating after certain events, either that or healthModifier is acting up.

**Comment by nutellka** [comment]
a da się to jakoś ściągnąć?

**Comment by bconlon1** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-aether/files/3155464 @nutellka
