### ISSUE TITLE
Crafting Guide button darkens when putting on enchanted Elytra?

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether-Archived#33]
yes GUI bug don't blame me

https://youtu.be/tXXKTOlhwHo

**Comment by bconlon1** [comment]
The accessory icon bug is reported in #8.

**Comment by bconlon1** [comment]
Has something to do with an OpenGL state not being restored properly. So somewhere in some rendering code it's not being properly reset or something.
