### ISSUE TITLE
Arrows are capable of teleporting through portals. This should not happen.

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether-Archived#36]
so i sent an arrow through a portal in 1.12 aether and after that tps dropped to 0 maybe bc its trying to generate both dimensions
causing massive lag spikes
![2020-12-08_15 39 12](https://user-images.githubusercontent.com/75763838/101708467-251f6880-3a42-11eb-9db6-c44d7fe583b2.png)
i may not have clear proof but ye uh ill send asap when i get new one

**Comment by bconlon1** [comment]
Technically a vanilla issue.
