### ISSUE TITLE
Arrows don't despawn when bouncing off aerclouds because the collision probably resets their life counter.

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether-Archived#41]
arrows wont despawn upon bouncing on blue aerclouds and if you log off and come back on it makes it worse both on singleplayer and mutliplayer, works on aether 1 and 2

![2020-12-08_12 32 48](https://user-images.githubusercontent.com/75763838/102531389-12ff8480-4057-11eb-899a-ca33257c0790.png)

**Comment by bconlon1** [comment]
Just gonna not bother with this one, it doesn't seem too major of an issue.
