### ISSUE TITLE
Floating Blocks not dropping items?

### ISSUE THREAD

**Issue by OfficialGDog** [Gilded-Games/The-Aether-Archived#48]
Right-clicking a block with gravitite tools (if there is nothing obstructing the floating block) no longer drops the block items when it reaches the sky limit (which is not the case in previous versions).

Video:
https://user-images.githubusercontent.com/40968181/103181312-bb072000-4897-11eb-88a2-c0b1f5f51e26.mp4

I was made aware of this issue from a player on my server MoaCraft who reported this issue after losing several Gravitite blocks I felt it was necessary to speak up and tell the developers about this since it's quite bad.

At first, I thought this was just a server-side issue. However, after testing this in a singleplayer world, I can confirm this is a bug with the mod failing to drop the item from the block once it reaches the sky limit.

Hopefully, this can be fixed in the next update otherwise a fantastic mod ⭐⭐⭐⭐⭐

**Comment by bconlon1** [comment]
Fixed; will be in next patch.
