### ISSUE TITLE
Darts seem to be causing a crash for possibly Dynamic Surroundings related reasons.

### ISSUE THREAD

**Issue by PopcornHead51** [Gilded-Games/The-Aether-Archived#53]
When attacked by a cockatrice or aechor plant with dynamic surroundings installed the game crashes. From what I can this happens on all 1.7.10 versions.
[crash-2020-12-30_15.28.43-server.txt](https://github.com/Gilded-Games/The-Aether-Archived/files/5755631/crash-2020-12-30_15.28.43-server.txt)
[crash-2020-12-30_15.23.30-server.txt](https://github.com/Gilded-Games/The-Aether-Archived/files/5755632/crash-2020-12-30_15.23.30-server.txt)

**Comment by bconlon1** [comment]
Fixed and will be in the next release.
