### ISSUE TITLE
Game crashes when right clicking with an empty bucket

### ISSUE THREAD

**Issue by TCreopargh** [Gilded-Games/The-Aether-Archived#59]
Whenever I right click water with empty bucket, the game crashes.
Crash report: https://paste.ubuntu.com/p/fr4Sn2xMbP/

(Update: not only water, trying to fill bucket with any liquid crashes the game)
(Update 2: It crashes whenever I right click with empty bucket in my hand)

Note: only happens with v1.5.3 (minecraft 1.12)

**Comment by bconlon1** [comment]
I will look into this asap tomorrow and release a patched version once I have a fix.

**Comment by Vaex** [comment]
same happens here too. 

Aether: aether-1.12.2-v1.5.3
MC: 1.2.12
Forge: 14.23.5.2854

And thanks for take a look on it @bconlon1

**Comment by bconlon1** [comment]
Fixed issue, the 1.5.3 build will be patched with the fix as soon as I can (in roughly 30 minutes). You will have to redownload the build to get the fix.

**Comment by bconlon1** [comment]
Build is now up on curseforge.
