### ISSUE TITLE
alter dose not repair swords 

### ISSUE THREAD

**Issue by catbryce** [Gilded-Games/The-Aether-Archived#60]
1.7.10 v1.1.2

**Comment by bconlon1** [comment]
Please elaborate on your issue.

**Comment by bconlon1** [comment]
Nevermind I now see your issue. Weird.

**Comment by bconlon1** [comment]
Figured out the cause, will put this in a patched build of 1.1.2

**Comment by bconlon1** [comment]
To get the fix you'll have to redownload in roughly half an hour.

**Comment by bconlon1** [comment]
The build is now up.
