### ISSUE TITLE
Using a bucket on certain liquids causes crash to desktop

### ISSUE THREAD

**Issue by George0079** [Gilded-Games/The-Aether-Archived#66]
I'm making a custom modpack, and a mod confict I've found between this mod and Tinker's Construct is a crash to desktop whenever picking up purple slime with a bucket. I'm still trying to test the specifics, but since I have to wait for my client to reopen MC I figured I'd send my latest crashlog.
I suspect that some code involving the skyroot buckets might be the cause, since that's about the only way this mod meddles with fluids.

I plan on bugtesting with a few more isolated mods to find the exact cause of the conflict. Luckily my pack is only at 70 mods so it should be easy to sift through them and find the conflict.
Figured I'd start searching for help here since the crashlog specifically says:
> at java.util.Objects.requireNonNull(Objects.java:203) at com.gildedgames.the_aether.AetherEventHandler.onFillBucket(AetherEventHandler.java:135)

Here's the full crashlog:
[crash-2021-01-03_15.10.54-client.txt](https://github.com/Gilded-Games/The-Aether-Archived/files/5762309/crash-2021-01-03_15.10.54-client.txt)

**Comment by bconlon1** [comment]
Try redownloading the 1.5.3 version from Curseforge, this should be patched by a re-release of the version.
