### ISSUE TITLE
(1.12.2) The Valk dungeon not working properly

### ISSUE THREAD

**Issue by DiamondKing1306** [Gilded-Games/The-Aether-Archived#81]
On this modpack im on the dungeon for valk queen isnt really working. When ever I beat the boss it doesnt open up the chest, and i cant break any of the blocks.

**Comment by bconlon1** [comment]
Please post a mod list or what the modpack you are using is.

**Comment by bconlon1** [comment]
Without the modpack list I can't do much about this issue.
