### ISSUE TITLE
Second hand layer renders on top of equipped gloves in first person

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether-Archived#85]
Example:
![2021-01-27_04 05 49](https://user-images.githubusercontent.com/52297970/106071163-c1d6bc00-60fd-11eb-9787-71cede97e90f.png)

Note how they render on top in third person:
![2021-01-27_04 05 54](https://user-images.githubusercontent.com/52297970/106071181-c9966080-60fd-11eb-86e2-b5048412bbd0.png)

Fix could be to make gloves render slightly off of the hand in first person to be consistent with how they do in third person, but apparently them being flush with the hand is a stylistic choice and there's an option to change it somewhere so I'm not entirely sure.

**Comment by bconlon1** [comment]
In skin customization settings you can toggle the layer that gloves render on in first person, so if you toggle it to the hat layer it'll render above any hat layer parts of your skin.
