### ISSUE TITLE
Plants added by the mod cannot be placed inside of flower pots

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether-Archived#93]
I can see this being difficult to implement in 1.12.2 due to vanilla's terrible handling of flower pots but in 1.13+ it should be fine. If this can't be done in 1.12.2 this ticket could be moved over to the 1.16+ project.

Plants affected:
- purple flower
- white flower
- skyroot sapling
- golden oak sapling
- berry bush (debatable; perhaps breaks consistency with vanilla logic, but for 1.14+ the Quark mod allows for sweet berry bushes to be placed in flower pots, so this could be added for consistency with that and only allowed to be placed inside if Quark is also currently installed, or could just be allowed regardless)

![2021-01-28_01 11 15](https://user-images.githubusercontent.com/52297970/106075911-71b02780-6106-11eb-8d04-e57468c1bd92.png)
![2021-01-28_01 11 21](https://user-images.githubusercontent.com/52297970/106075912-72e15480-6106-11eb-9e1e-713e864622f9.png)
![2021-01-28_01 11 32](https://user-images.githubusercontent.com/52297970/106075914-74128180-6106-11eb-97a1-b90260f03f7e.png)
![2021-01-28_01 11 53](https://user-images.githubusercontent.com/52297970/106075915-74ab1800-6106-11eb-8465-432666d46e3c.png)

**Comment by bconlon1** [comment]
Basically impossible in 1.12.

**Comment by muzikbike** [comment]
Could this be moved then?
