### ISSUE TITLE
Ambrosium Shards turn any block into Enchanted Aether Grass

### ISSUE THREAD

**Issue by puncrafter** [Gilded-Games/The-Aether-Archived#97]
> The Aether Version: aether-1.12.2-v1.5.3.1
> Aether Continuation Version: Aether Continuation v1.3.0
> Aether: Lost Content Verion: lost-aether-content-1.12.2-1.0.2

I'm not entirely sure which of these mods causes this interaction, but the issue is exactly as it is said in the title. Presumably, creating enchanted aether grass is only supposed to work on aether grass and aether dirt, but you can right-click ambrosium shards onto any block, including non-aether blocks.

**Comment by fullskele** [comment]
I'm having the same issue. This only occurs in the Aether dimension, as using it in the Overworld just results in you eating the Ambrosium Shard.

**Comment by DuckyIsEpic** [comment]
I'm having this issue too, you can also use it on dungeon blocks allowing the slider to escape his dungeon and destroy the world. Quite funny though.
